spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    initialization-mode: never

  flyway:
    enabled: true
    locations:
    - classpath:/db/migration

  jackson:
    default-property-inclusion: non-null
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true 
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - flyway

logging:
  level:
    web: TRACE
    org.springframework.web: TRACE